name: IoMBian builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          image-name: iombian
          release: bookworm
          pi-gen-release: IoMBian
          pi-gen-version: arm64
          username: iompi
          password: iompi
          hostname: iombian
          disable-first-boot-user-rename: 1
          stage-list: stage0 stage1 stage2 stage6
          verbose-output: true